// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarsServiceClient is the client API for CarsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarsServiceClient interface {
	GetCar(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarResponse, error)
}

type carsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarsServiceClient(cc grpc.ClientConnInterface) CarsServiceClient {
	return &carsServiceClient{cc}
}

func (c *carsServiceClient) GetCar(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarResponse, error) {
	out := new(CarResponse)
	err := c.cc.Invoke(ctx, "/cars.CarsService/GetCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarsServiceServer is the server API for CarsService service.
// All implementations must embed UnimplementedCarsServiceServer
// for forward compatibility
type CarsServiceServer interface {
	GetCar(context.Context, *CarRequest) (*CarResponse, error)
	mustEmbedUnimplementedCarsServiceServer()
}

// UnimplementedCarsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCarsServiceServer struct {
}

func (UnimplementedCarsServiceServer) GetCar(context.Context, *CarRequest) (*CarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCar not implemented")
}
func (UnimplementedCarsServiceServer) mustEmbedUnimplementedCarsServiceServer() {}

// UnsafeCarsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarsServiceServer will
// result in compilation errors.
type UnsafeCarsServiceServer interface {
	mustEmbedUnimplementedCarsServiceServer()
}

func RegisterCarsServiceServer(s grpc.ServiceRegistrar, srv CarsServiceServer) {
	s.RegisterService(&CarsService_ServiceDesc, srv)
}

func _CarsService_GetCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServiceServer).GetCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cars.CarsService/GetCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServiceServer).GetCar(ctx, req.(*CarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarsService_ServiceDesc is the grpc.ServiceDesc for CarsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cars.CarsService",
	HandlerType: (*CarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCar",
			Handler:    _CarsService_GetCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cars.proto",
}
